/* Generated by tools/bsp_vis.py -- do not edit. Each level's draw
 * programs go in its banked window section beside its wall pack. */

    .section .wallpack0,"a"
    .align  2
    .globl  megaldoom_vis_program_e1m1
megaldoom_vis_program_e1m1: /* 237 leaves, 31346 words, longest 351 */
    .incbin "src/bsp/generated_bsp_vis_e1m1.dat"

    .section .wallpack1,"a"
    .align  2
    .globl  megaldoom_vis_program_e1m2
megaldoom_vis_program_e1m2: /* 448 leaves, 56002 words, longest 988 */
    .incbin "src/bsp/generated_bsp_vis_e1m2.dat"

    .section .wallpack2,"a"
    .align  2
    .globl  megaldoom_vis_program_e1m3
megaldoom_vis_program_e1m3: /* 461 leaves, 52813 words, longest 373 */
    .incbin "src/bsp/generated_bsp_vis_e1m3.dat"

    .section .wallpack3,"a"
    .align  2
    .globl  megaldoom_vis_program_e1m4
megaldoom_vis_program_e1m4: /* 355 leaves, 37355 words, longest 297 */
    .incbin "src/bsp/generated_bsp_vis_e1m4.dat"

    .section .wallpack4,"a"
    .align  2
    .globl  megaldoom_vis_program_e1m5
megaldoom_vis_program_e1m5: /* 384 leaves, 52565 words, longest 469 */
    .incbin "src/bsp/generated_bsp_vis_e1m5.dat"

    .section .wallpack5,"a"
    .align  2
    .globl  megaldoom_vis_program_e1m6
megaldoom_vis_program_e1m6: /* 606 leaves, 83698 words, longest 986 */
    .incbin "src/bsp/generated_bsp_vis_e1m6.dat"

    .section .wallpack6,"a"
    .align  2
    .globl  megaldoom_vis_program_e1m7
megaldoom_vis_program_e1m7: /* 467 leaves, 78526 words, longest 426 */
    .incbin "src/bsp/generated_bsp_vis_e1m7.dat"
