/* Generated by tools/world_assets.emit_level_wall_packs.
 *
 * Pack N goes in section .wallpackN, which tools/md_banked.ld links at the
 * 0x280000 level window and loads at that level's own physical banks.
 * megaldoom_level_{wall,door}_bases hold, per level and global texture id,
 * the window address of that texture's 32 KB block; they are resident and
 * only dereferenced while the level's banks are mapped. A wall entry for
 * an id the level never draws points at its fallback block; a door entry
 * of 0 means the texture has no door framing in that level. */

    .section .wallpack0,"a"
    .globl megaldoom_wallpack0
megaldoom_wallpack0: /* E1M1 */
    .incbin "src/bsp/generated_wallpack_e1m1.dat"

    .section .wallpack1,"a"
    .globl megaldoom_wallpack1
megaldoom_wallpack1: /* E1M2 */
    .incbin "src/bsp/generated_wallpack_e1m2.dat"

    .section .wallpack2,"a"
    .globl megaldoom_wallpack2
megaldoom_wallpack2: /* E1M3 */
    .incbin "src/bsp/generated_wallpack_e1m3.dat"

    .section .wallpack3,"a"
    .globl megaldoom_wallpack3
megaldoom_wallpack3: /* E1M4 */
    .incbin "src/bsp/generated_wallpack_e1m4.dat"

    .section .rodata.megaldoom_level_wall_bases,"a"
    .align 2
    .globl megaldoom_level_wall_bases
megaldoom_level_wall_bases:
    /* E1M1 */
    .long megaldoom_wallpack0+0 /* __FALLBACK__ */
    .long megaldoom_wallpack0+0 /* BIGDOOR1 */
    .long megaldoom_wallpack0+32768 /* BIGDOOR2 */
    .long megaldoom_wallpack0+65536 /* BIGDOOR4 */
    .long megaldoom_wallpack0+0 /* BRNPOIS */
    .long megaldoom_wallpack0+98304 /* BROWN1 */
    .long megaldoom_wallpack0+131072 /* BROWN144 */
    .long megaldoom_wallpack0+163840 /* BROWN96 */
    .long megaldoom_wallpack0+196608 /* BROWNGRN */
    .long megaldoom_wallpack0+0 /* BROWNHUG */
    .long megaldoom_wallpack0+0 /* COMPSPAN */
    .long megaldoom_wallpack0+229376 /* COMPTALL */
    .long megaldoom_wallpack0+262144 /* DOOR1 */
    .long megaldoom_wallpack0+0 /* DOORBLU */
    .long megaldoom_wallpack0+0 /* DOORRED */
    .long megaldoom_wallpack0+294912 /* DOORSTOP */
    .long megaldoom_wallpack0+327680 /* DOORTRAK */
    .long megaldoom_wallpack0+0 /* DOORYEL */
    .long megaldoom_wallpack0+360448 /* EXITDOOR */
    .long megaldoom_wallpack0+0 /* LITE2 */
    .long megaldoom_wallpack0+393216 /* LITE3 */
    .long megaldoom_wallpack0+0 /* LITEBLU3 */
    .long megaldoom_wallpack0+0 /* METAL1 */
    .long megaldoom_wallpack0+0 /* NUKE24 */
    .long megaldoom_wallpack0+0 /* PIPE2 */
    .long megaldoom_wallpack0+0 /* PLAT1 */
    .long megaldoom_wallpack0+0 /* SLADWALL */
    .long megaldoom_wallpack0+425984 /* STARG3 */
    .long megaldoom_wallpack0+458752 /* STARGR1 */
    .long megaldoom_wallpack0+491520 /* STARTAN1 */
    .long megaldoom_wallpack0+0 /* STARTAN2 */
    .long megaldoom_wallpack0+524288 /* STARTAN3 */
    .long megaldoom_wallpack0+0 /* STEP2 */
    .long megaldoom_wallpack0+0 /* STONE */
    .long megaldoom_wallpack0+0 /* STONE2 */
    .long megaldoom_wallpack0+557056 /* SUPPORT2 */
    .long megaldoom_wallpack0+0 /* SW1COMP */
    .long megaldoom_wallpack0+0 /* SW1METAL */
    .long megaldoom_wallpack0+589824 /* SW1STRTN */
    .long megaldoom_wallpack0+0 /* SW2BROWN */
    .long megaldoom_wallpack0+0 /* TEKWALL1 */
    .long megaldoom_wallpack0+0 /* TEKWALL4 */
    .long megaldoom_wallpack0+0 /* TEKWALL5 */
    /* E1M2 */
    .long megaldoom_wallpack1+0 /* __FALLBACK__ */
    .long megaldoom_wallpack1+0 /* BIGDOOR1 */
    .long megaldoom_wallpack1+32768 /* BIGDOOR2 */
    .long megaldoom_wallpack1+0 /* BIGDOOR4 */
    .long megaldoom_wallpack1+0 /* BRNPOIS */
    .long megaldoom_wallpack1+65536 /* BROWN1 */
    .long megaldoom_wallpack1+98304 /* BROWN144 */
    .long megaldoom_wallpack1+0 /* BROWN96 */
    .long megaldoom_wallpack1+131072 /* BROWNGRN */
    .long megaldoom_wallpack1+163840 /* BROWNHUG */
    .long megaldoom_wallpack1+0 /* COMPSPAN */
    .long megaldoom_wallpack1+196608 /* COMPTALL */
    .long megaldoom_wallpack1+229376 /* DOOR1 */
    .long megaldoom_wallpack1+0 /* DOORBLU */
    .long megaldoom_wallpack1+262144 /* DOORRED */
    .long megaldoom_wallpack1+294912 /* DOORSTOP */
    .long megaldoom_wallpack1+327680 /* DOORTRAK */
    .long megaldoom_wallpack1+0 /* DOORYEL */
    .long megaldoom_wallpack1+360448 /* EXITDOOR */
    .long megaldoom_wallpack1+0 /* LITE2 */
    .long megaldoom_wallpack1+393216 /* LITE3 */
    .long megaldoom_wallpack1+425984 /* LITEBLU3 */
    .long megaldoom_wallpack1+458752 /* METAL1 */
    .long megaldoom_wallpack1+0 /* NUKE24 */
    .long megaldoom_wallpack1+491520 /* PIPE2 */
    .long megaldoom_wallpack1+0 /* PLAT1 */
    .long megaldoom_wallpack1+524288 /* SLADWALL */
    .long megaldoom_wallpack1+557056 /* STARG3 */
    .long megaldoom_wallpack1+0 /* STARGR1 */
    .long megaldoom_wallpack1+0 /* STARTAN1 */
    .long megaldoom_wallpack1+589824 /* STARTAN2 */
    .long megaldoom_wallpack1+622592 /* STARTAN3 */
    .long megaldoom_wallpack1+0 /* STEP2 */
    .long megaldoom_wallpack1+0 /* STONE */
    .long megaldoom_wallpack1+655360 /* STONE2 */
    .long megaldoom_wallpack1+688128 /* SUPPORT2 */
    .long megaldoom_wallpack1+720896 /* SW1COMP */
    .long megaldoom_wallpack1+0 /* SW1METAL */
    .long megaldoom_wallpack1+0 /* SW1STRTN */
    .long megaldoom_wallpack1+0 /* SW2BROWN */
    .long megaldoom_wallpack1+753664 /* TEKWALL1 */
    .long megaldoom_wallpack1+786432 /* TEKWALL4 */
    .long megaldoom_wallpack1+819200 /* TEKWALL5 */
    /* E1M3 */
    .long megaldoom_wallpack2+0 /* __FALLBACK__ */
    .long megaldoom_wallpack2+0 /* BIGDOOR1 */
    .long megaldoom_wallpack2+32768 /* BIGDOOR2 */
    .long megaldoom_wallpack2+65536 /* BIGDOOR4 */
    .long megaldoom_wallpack2+0 /* BRNPOIS */
    .long megaldoom_wallpack2+98304 /* BROWN1 */
    .long megaldoom_wallpack2+131072 /* BROWN144 */
    .long megaldoom_wallpack2+163840 /* BROWN96 */
    .long megaldoom_wallpack2+196608 /* BROWNGRN */
    .long megaldoom_wallpack2+229376 /* BROWNHUG */
    .long megaldoom_wallpack2+0 /* COMPSPAN */
    .long megaldoom_wallpack2+262144 /* COMPTALL */
    .long megaldoom_wallpack2+294912 /* DOOR1 */
    .long megaldoom_wallpack2+327680 /* DOORBLU */
    .long megaldoom_wallpack2+0 /* DOORRED */
    .long megaldoom_wallpack2+360448 /* DOORSTOP */
    .long megaldoom_wallpack2+393216 /* DOORTRAK */
    .long megaldoom_wallpack2+425984 /* DOORYEL */
    .long megaldoom_wallpack2+458752 /* EXITDOOR */
    .long megaldoom_wallpack2+0 /* LITE2 */
    .long megaldoom_wallpack2+491520 /* LITE3 */
    .long megaldoom_wallpack2+524288 /* LITEBLU3 */
    .long megaldoom_wallpack2+557056 /* METAL1 */
    .long megaldoom_wallpack2+0 /* NUKE24 */
    .long megaldoom_wallpack2+0 /* PIPE2 */
    .long megaldoom_wallpack2+0 /* PLAT1 */
    .long megaldoom_wallpack2+589824 /* SLADWALL */
    .long megaldoom_wallpack2+622592 /* STARG3 */
    .long megaldoom_wallpack2+655360 /* STARGR1 */
    .long megaldoom_wallpack2+688128 /* STARTAN1 */
    .long megaldoom_wallpack2+720896 /* STARTAN2 */
    .long megaldoom_wallpack2+753664 /* STARTAN3 */
    .long megaldoom_wallpack2+0 /* STEP2 */
    .long megaldoom_wallpack2+786432 /* STONE */
    .long megaldoom_wallpack2+819200 /* STONE2 */
    .long megaldoom_wallpack2+851968 /* SUPPORT2 */
    .long megaldoom_wallpack2+884736 /* SW1COMP */
    .long megaldoom_wallpack2+0 /* SW1METAL */
    .long megaldoom_wallpack2+0 /* SW1STRTN */
    .long megaldoom_wallpack2+0 /* SW2BROWN */
    .long megaldoom_wallpack2+917504 /* TEKWALL1 */
    .long megaldoom_wallpack2+950272 /* TEKWALL4 */
    .long megaldoom_wallpack2+983040 /* TEKWALL5 */
    /* E1M4 */
    .long megaldoom_wallpack3+0 /* __FALLBACK__ */
    .long megaldoom_wallpack3+32768 /* BIGDOOR1 */
    .long megaldoom_wallpack3+65536 /* BIGDOOR2 */
    .long megaldoom_wallpack3+98304 /* BIGDOOR4 */
    .long megaldoom_wallpack3+131072 /* BRNPOIS */
    .long megaldoom_wallpack3+163840 /* BROWN1 */
    .long megaldoom_wallpack3+196608 /* BROWN144 */
    .long megaldoom_wallpack3+229376 /* BROWN96 */
    .long megaldoom_wallpack3+262144 /* BROWNGRN */
    .long megaldoom_wallpack3+0 /* BROWNHUG */
    .long megaldoom_wallpack3+294912 /* COMPSPAN */
    .long megaldoom_wallpack3+327680 /* COMPTALL */
    .long megaldoom_wallpack3+360448 /* DOOR1 */
    .long megaldoom_wallpack3+393216 /* DOORBLU */
    .long megaldoom_wallpack3+0 /* DOORRED */
    .long megaldoom_wallpack3+425984 /* DOORSTOP */
    .long megaldoom_wallpack3+458752 /* DOORTRAK */
    .long megaldoom_wallpack3+491520 /* DOORYEL */
    .long megaldoom_wallpack3+524288 /* EXITDOOR */
    .long megaldoom_wallpack3+557056 /* LITE2 */
    .long megaldoom_wallpack3+589824 /* LITE3 */
    .long megaldoom_wallpack3+0 /* LITEBLU3 */
    .long megaldoom_wallpack3+622592 /* METAL1 */
    .long megaldoom_wallpack3+655360 /* NUKE24 */
    .long megaldoom_wallpack3+0 /* PIPE2 */
    .long megaldoom_wallpack3+688128 /* PLAT1 */
    .long megaldoom_wallpack3+720896 /* SLADWALL */
    .long megaldoom_wallpack3+753664 /* STARG3 */
    .long megaldoom_wallpack3+786432 /* STARGR1 */
    .long megaldoom_wallpack3+0 /* STARTAN1 */
    .long megaldoom_wallpack3+0 /* STARTAN2 */
    .long megaldoom_wallpack3+819200 /* STARTAN3 */
    .long megaldoom_wallpack3+851968 /* STEP2 */
    .long megaldoom_wallpack3+884736 /* STONE */
    .long megaldoom_wallpack3+917504 /* STONE2 */
    .long megaldoom_wallpack3+950272 /* SUPPORT2 */
    .long megaldoom_wallpack3+983040 /* SW1COMP */
    .long megaldoom_wallpack3+1015808 /* SW1METAL */
    .long megaldoom_wallpack3+0 /* SW1STRTN */
    .long megaldoom_wallpack3+1048576 /* SW2BROWN */
    .long megaldoom_wallpack3+0 /* TEKWALL1 */
    .long megaldoom_wallpack3+0 /* TEKWALL4 */
    .long megaldoom_wallpack3+1081344 /* TEKWALL5 */

    .section .rodata.megaldoom_level_door_bases,"a"
    .align 2
    .globl megaldoom_level_door_bases
megaldoom_level_door_bases:
    /* E1M1 */
    .long 0 /* __FALLBACK__ */
    .long 0 /* BIGDOOR1 */
    .long megaldoom_wallpack0+622592 /* BIGDOOR2 */
    .long megaldoom_wallpack0+655360 /* BIGDOOR4 */
    .long 0 /* BRNPOIS */
    .long 0 /* BROWN1 */
    .long 0 /* BROWN144 */
    .long 0 /* BROWN96 */
    .long 0 /* BROWNGRN */
    .long 0 /* BROWNHUG */
    .long 0 /* COMPSPAN */
    .long 0 /* COMPTALL */
    .long 0 /* DOOR1 */
    .long 0 /* DOORBLU */
    .long 0 /* DOORRED */
    .long 0 /* DOORSTOP */
    .long 0 /* DOORTRAK */
    .long 0 /* DOORYEL */
    .long megaldoom_wallpack0+688128 /* EXITDOOR */
    .long 0 /* LITE2 */
    .long 0 /* LITE3 */
    .long 0 /* LITEBLU3 */
    .long 0 /* METAL1 */
    .long 0 /* NUKE24 */
    .long 0 /* PIPE2 */
    .long 0 /* PLAT1 */
    .long 0 /* SLADWALL */
    .long 0 /* STARG3 */
    .long 0 /* STARGR1 */
    .long 0 /* STARTAN1 */
    .long 0 /* STARTAN2 */
    .long 0 /* STARTAN3 */
    .long 0 /* STEP2 */
    .long 0 /* STONE */
    .long 0 /* STONE2 */
    .long 0 /* SUPPORT2 */
    .long 0 /* SW1COMP */
    .long 0 /* SW1METAL */
    .long 0 /* SW1STRTN */
    .long 0 /* SW2BROWN */
    .long 0 /* TEKWALL1 */
    .long 0 /* TEKWALL4 */
    .long 0 /* TEKWALL5 */
    /* E1M2 */
    .long 0 /* __FALLBACK__ */
    .long 0 /* BIGDOOR1 */
    .long megaldoom_wallpack1+851968 /* BIGDOOR2 */
    .long 0 /* BIGDOOR4 */
    .long 0 /* BRNPOIS */
    .long megaldoom_wallpack1+884736 /* BROWN1 */
    .long 0 /* BROWN144 */
    .long 0 /* BROWN96 */
    .long megaldoom_wallpack1+917504 /* BROWNGRN */
    .long 0 /* BROWNHUG */
    .long 0 /* COMPSPAN */
    .long 0 /* COMPTALL */
    .long 0 /* DOOR1 */
    .long 0 /* DOORBLU */
    .long 0 /* DOORRED */
    .long 0 /* DOORSTOP */
    .long 0 /* DOORTRAK */
    .long 0 /* DOORYEL */
    .long megaldoom_wallpack1+950272 /* EXITDOOR */
    .long 0 /* LITE2 */
    .long 0 /* LITE3 */
    .long 0 /* LITEBLU3 */
    .long 0 /* METAL1 */
    .long 0 /* NUKE24 */
    .long megaldoom_wallpack1+983040 /* PIPE2 */
    .long 0 /* PLAT1 */
    .long 0 /* SLADWALL */
    .long 0 /* STARG3 */
    .long 0 /* STARGR1 */
    .long 0 /* STARTAN1 */
    .long 0 /* STARTAN2 */
    .long 0 /* STARTAN3 */
    .long 0 /* STEP2 */
    .long 0 /* STONE */
    .long 0 /* STONE2 */
    .long 0 /* SUPPORT2 */
    .long 0 /* SW1COMP */
    .long 0 /* SW1METAL */
    .long 0 /* SW1STRTN */
    .long 0 /* SW2BROWN */
    .long 0 /* TEKWALL1 */
    .long 0 /* TEKWALL4 */
    .long 0 /* TEKWALL5 */
    /* E1M3 */
    .long 0 /* __FALLBACK__ */
    .long 0 /* BIGDOOR1 */
    .long megaldoom_wallpack2+1015808 /* BIGDOOR2 */
    .long megaldoom_wallpack2+1048576 /* BIGDOOR4 */
    .long 0 /* BRNPOIS */
    .long 0 /* BROWN1 */
    .long 0 /* BROWN144 */
    .long 0 /* BROWN96 */
    .long 0 /* BROWNGRN */
    .long 0 /* BROWNHUG */
    .long 0 /* COMPSPAN */
    .long 0 /* COMPTALL */
    .long 0 /* DOOR1 */
    .long 0 /* DOORBLU */
    .long 0 /* DOORRED */
    .long 0 /* DOORSTOP */
    .long 0 /* DOORTRAK */
    .long 0 /* DOORYEL */
    .long megaldoom_wallpack2+1081344 /* EXITDOOR */
    .long 0 /* LITE2 */
    .long 0 /* LITE3 */
    .long 0 /* LITEBLU3 */
    .long megaldoom_wallpack2+1114112 /* METAL1 */
    .long 0 /* NUKE24 */
    .long 0 /* PIPE2 */
    .long 0 /* PLAT1 */
    .long 0 /* SLADWALL */
    .long 0 /* STARG3 */
    .long 0 /* STARGR1 */
    .long 0 /* STARTAN1 */
    .long megaldoom_wallpack2+1146880 /* STARTAN2 */
    .long megaldoom_wallpack2+1179648 /* STARTAN3 */
    .long 0 /* STEP2 */
    .long 0 /* STONE */
    .long megaldoom_wallpack2+1212416 /* STONE2 */
    .long 0 /* SUPPORT2 */
    .long 0 /* SW1COMP */
    .long 0 /* SW1METAL */
    .long 0 /* SW1STRTN */
    .long 0 /* SW2BROWN */
    .long megaldoom_wallpack2+1245184 /* TEKWALL1 */
    .long megaldoom_wallpack2+1277952 /* TEKWALL4 */
    .long megaldoom_wallpack2+1310720 /* TEKWALL5 */
    /* E1M4 */
    .long 0 /* __FALLBACK__ */
    .long megaldoom_wallpack3+1114112 /* BIGDOOR1 */
    .long megaldoom_wallpack3+1146880 /* BIGDOOR2 */
    .long megaldoom_wallpack3+1179648 /* BIGDOOR4 */
    .long 0 /* BRNPOIS */
    .long 0 /* BROWN1 */
    .long 0 /* BROWN144 */
    .long 0 /* BROWN96 */
    .long 0 /* BROWNGRN */
    .long 0 /* BROWNHUG */
    .long 0 /* COMPSPAN */
    .long 0 /* COMPTALL */
    .long megaldoom_wallpack3+1212416 /* DOOR1 */
    .long 0 /* DOORBLU */
    .long 0 /* DOORRED */
    .long 0 /* DOORSTOP */
    .long 0 /* DOORTRAK */
    .long 0 /* DOORYEL */
    .long megaldoom_wallpack3+1245184 /* EXITDOOR */
    .long 0 /* LITE2 */
    .long 0 /* LITE3 */
    .long 0 /* LITEBLU3 */
    .long 0 /* METAL1 */
    .long 0 /* NUKE24 */
    .long 0 /* PIPE2 */
    .long 0 /* PLAT1 */
    .long 0 /* SLADWALL */
    .long 0 /* STARG3 */
    .long 0 /* STARGR1 */
    .long 0 /* STARTAN1 */
    .long 0 /* STARTAN2 */
    .long 0 /* STARTAN3 */
    .long megaldoom_wallpack3+1277952 /* STEP2 */
    .long megaldoom_wallpack3+1310720 /* STONE */
    .long 0 /* STONE2 */
    .long 0 /* SUPPORT2 */
    .long 0 /* SW1COMP */
    .long 0 /* SW1METAL */
    .long 0 /* SW1STRTN */
    .long 0 /* SW2BROWN */
    .long 0 /* TEKWALL1 */
    .long 0 /* TEKWALL4 */
    .long 0 /* TEKWALL5 */
