#!/usr/bin/env python3
"""Render a flattened Doom map (doom_map.MapData) plus its resolved texture
ids (from world_assets.emit_world_assets) as MegalDoom's generated_<map>_map.c.

Also builds and validates the runtime collision/LOS blockmap: that array is
pure emission output (baked once, read every frame by the renderer), so it is
derived here rather than inside doom_map.load_map().
"""

import os
from dataclasses import dataclass

from doom_map import validate_spatial_grid

WALL_TEX_WIDTH = None
WALL_TEX_HEIGHT = None  # set before emit_map_c() is called


def set_wall_tex_dims(width, height):
    global WALL_TEX_WIDTH, WALL_TEX_HEIGHT
    WALL_TEX_WIDTH = width
    WALL_TEX_HEIGHT = height


@dataclass
class EmitReport:
    root: int
    grid_width: int
    grid_height: int
    grid_ref_count: int
    spatial_checks: int


def emit_map_c(path, wad_path, map_data, texture_ids, texture_meta):
    out_segs = map_data.out_segs
    vertices = map_data.vertices
    nodes = map_data.nodes
    prefix = map_data.mapn.lower()

    def sym(name):
        return "%s_%s" % (prefix, name)

    for seg in out_segs:
        name = seg["texture_name"]
        if not -32768 <= seg["tex_u_offset"] <= 32767:
            raise SystemExit("texture U offset out of s16 range: %d" % seg["tex_u_offset"])
        seg["tex"] = texture_ids[name]
        source_height = texture_meta[name]["height"]
        seg["tex_v"] = ((seg["tex_v_offset"] * WALL_TEX_HEIGHT) //
                        source_height) & (WALL_TEX_HEIGHT - 1)

    root = (len(nodes) - 1) if nodes else 0x8000

    lines = []
    lines.append("// Generated by tools/wad-map-extract.py")
    lines.append("// Source: %s  map: %s" % (os.path.basename(wad_path), map_data.mapn))
    lines.append("// Source SHA-256: %s" % map_data.wad_sha256)
    lines.append("// Flat baseline/final: %d/%d SEGs; curated material: %d linedefs / %d SEGs" % (
        map_data.baseline_seg_count, len(out_segs),
        len(map_data.curated_material_linedefs), map_data.curated_material_segs))
    for transfer in map_data.curated_material_reports:
        lines.append(
            "// Curated material: %s source linedef %d (hint %d) -> targets %s, %s, %d retextured, +%d SEGs" % (
                transfer["name"], transfer["source_linedef"],
                transfer["source_linedef_hint"],
                ",".join(str(value) for value in transfer["target_linedefs"]),
                transfer["texture"], transfer["retextured_segs"],
                transfer["added_segs"]))
    lines.append("// Certified: exit SEG %d reachable after %d states" % (
        map_data.certificate["exit_index"], map_data.certificate["states"]))
    lines.append("// Sky sectors (F_SKY1 ceiling): %d" % sum(
        1 for sector in map_data.sectors if sector["ceiling_name"] == "F_SKY1"))
    lines.append("// Generated at: source-derived")
    lines.append("#include \"bsp_map.h\"")
    lines.append("")

    lines.append("#if !BSP_USE_HAND_MAP")
    lines.append("")

    lines.append("static const BspAutomapLine %s[%d] = {" %
                 (sym("bsp_automap_lines"), len(map_data.automap_lines)))
    for line in map_data.automap_lines:
        lines.append("    {%d, %d, %d, %d, %d, %d}," % (
            line["v1"], line["v2"], line["front_sector"],
            line["back_sector"], line["kind"], line["flags"]))
    lines.append("};")
    lines.append("static const u16 %s[%d] = {" %
                 (sym("bsp_seg_automap_lines"), len(out_segs)))
    seg_automap = [map_data.linedef_automap_indices[s["source_linedef"]]
                   for s in out_segs]
    for i in range(0, len(seg_automap), 12):
        lines.append("    %s," % ",".join(
            "%du" % value for value in seg_automap[i:i + 12]))
    lines.append("};")
    lines.append("")

    # Vertices (full original array; segs/nodes reference these indices).
    lines.append("static const BspVertex %s[%d] = {" % (sym("bsp_vertices"), len(vertices)))
    for (x, y) in vertices:
        lines.append("    {%d, %d}," % (x, y))
    lines.append("};")
    lines.append("")

    lines.append("static const BspSeg %s[%d] = {" % (sym("bsp_segs"), len(out_segs)))
    for s in out_segs:
        lines.append("    {%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d}," % (
            s["v1"], s["v2"], s["nx"], s["ny"], s["tex_u_offset"],
            s["tex_v"], s["tex"], s["type"], s["door_group"], s["required_key"],
            s["flags"]))
    lines.append("};")
    lines.append("")

    # Compact parallel ROM table: precomputed wall length per seg (|bx-ax| +
    # |by-ay|). Camera-independent, stored in ROM to avoid two vertex lookups
    # and two abs calls per seg visit in the renderer hot path.
    lines.append("static const u16 %s[%d] = {" % (sym("bsp_seg_wall_len"), len(out_segs)))
    for i, s in enumerate(out_segs):
        ax, ay = vertices[s["v1"]]
        bx, by = vertices[s["v2"]]
        wl = abs(bx - ax) + abs(by - ay)
        if i % 12 == 0:
            # Start a new visual row. The previous row needs a trailing comma
            # so consecutive rows stay valid C (adjacent numeric tokens like
            # "128\n    128" would otherwise be a syntax error). The very first
            # row (i == 0) has no predecessor to terminate.
            if i > 0:
                lines[-1] += ","
            lines.append("    %d" % wl)
        else:
            lines[-1] += ",%d" % wl
    lines[-1] += ","
    lines.append("};")
    lines.append("")

    # Uniform 256-unit blockmap used by runtime collision and LOS.  A segment is
    # referenced by every cell touched by its AABB; the exact segment tests remain
    # authoritative, so this is a conservative broad phase rather than a geometry
    # approximation.  All arrays are const and therefore live in cartridge ROM.
    grid_cell = 256
    grid_min_x = (min(x for x, _ in vertices) // grid_cell) * grid_cell
    grid_min_y = (min(y for _, y in vertices) // grid_cell) * grid_cell
    grid_max_x = (max(x for x, _ in vertices) // grid_cell) * grid_cell
    grid_max_y = (max(y for _, y in vertices) // grid_cell) * grid_cell
    grid_w = ((grid_max_x - grid_min_x) // grid_cell) + 1
    grid_h = ((grid_max_y - grid_min_y) // grid_cell) + 1
    grid_cells = [[] for _ in range(grid_w * grid_h)]
    for seg_index, s in enumerate(out_segs):
        ax, ay = vertices[s["v1"]]
        bx, by = vertices[s["v2"]]
        cx0 = (min(ax, bx) - grid_min_x) // grid_cell
        cx1 = (max(ax, bx) - grid_min_x) // grid_cell
        cy0 = (min(ay, by) - grid_min_y) // grid_cell
        cy1 = (max(ay, by) - grid_min_y) // grid_cell
        for cy in range(cy0, cy1 + 1):
            for cx in range(cx0, cx1 + 1):
                grid_cells[cy * grid_w + cx].append(seg_index)

    grid_offsets = [0]
    grid_indices = []
    for cell in grid_cells:
        grid_indices.extend(cell)
        grid_offsets.append(len(grid_indices))

    spatial_checks = validate_spatial_grid(
        vertices, out_segs, grid_min_x, grid_min_y, grid_w, grid_h,
        grid_cell, grid_cells, map_data.start_x, map_data.start_y)

    lines.append("static const u16 %s[%d] = {" % (sym("bsp_grid_cell_offsets"), len(grid_offsets)))
    for i in range(0, len(grid_offsets), 12):
        lines.append("    %s," % ",".join(str(v) for v in grid_offsets[i:i + 12]))
    lines.append("};")
    lines.append("static const u16 %s[%d] = {" % (sym("bsp_grid_seg_indices"), len(grid_indices)))
    for i in range(0, len(grid_indices), 12):
        lines.append("    %s," % ",".join(str(v) for v in grid_indices[i:i + 12]))
    lines.append("};")
    lines.append("")

    lines.append("static const BspSubsector %s[%d] = {" %
                 (sym("bsp_subsectors"), len(map_data.out_ssectors)))
    for first, count in map_data.out_ssectors:
        lines.append("    {%d, %d}," % (first, count))
    lines.append("};")
    lines.append("static const u16 %s[%d] = {" %
                 (sym("bsp_subsector_sector"), len(map_data.out_ssector_sectors)))
    for i in range(0, len(map_data.out_ssector_sectors), 16):
        lines.append("    %s," % ",".join(
            str(value) for value in map_data.out_ssector_sectors[i:i + 16]))
    lines.append("};")
    lines.append("")

    lines.append("static const BspNode %s[%d] = {" % (sym("bsp_nodes"), len(nodes)))
    for nd in nodes:
        lines.append("    {%d, %d, %d, %d, {%d, %d, %d, %d}, {%d, %d, %d, %d}, %du, %du}," % (
            nd["x"], nd["y"], nd["dx"], nd["dy"],
            *nd["front_box"], *nd["back_box"], nd["front"], nd["back"]))
    lines.append("};")
    lines.append("")

    lines.append("static const BspThing %s[%d] = {" % (sym("bsp_things"), len(map_data.out_things)))
    for x, y, thing_type, angle, flags in map_data.out_things:
        lines.append("    {%d, %d, %du, %du, %du}," %
                     (x, y, thing_type, angle, flags))
    lines.append("};")
    secret_sector_ids = [index for index, sector in enumerate(map_data.sectors)
                         if sector["special"] == 9]
    secret_bits = [0] * ((len(map_data.sectors) + 7) // 8)
    for sector_id in secret_sector_ids:
        secret_bits[sector_id >> 3] |= 1 << (sector_id & 7)
    lines.append("static const u8 %s[%d] = {" %
                 (sym("bsp_secret_sector_bits"), len(secret_bits)))
    for i in range(0, len(secret_bits), 16):
        lines.append("    %s," % ",".join(str(value) for value in secret_bits[i:i + 16]))
    lines.append("};")

    # Per-sector "this ceiling is the sky" bitmap, same shape as the secret
    # bitmap above. Only the ceiling flat NAME is consulted; heights still never
    # enter the ROM (see doom_map's contract). The renderer reads this once per
    # frame for the player's sector to pick the sky ceiling table.
    sky_sector_ids = [index for index, sector in enumerate(map_data.sectors)
                      if sector["ceiling_name"] == "F_SKY1"]
    sky_bits = [0] * ((len(map_data.sectors) + 7) // 8)
    for sector_id in sky_sector_ids:
        sky_bits[sector_id >> 3] |= 1 << (sector_id & 7)
    lines.append("static const u8 %s[%d] = {" %
                 (sym("bsp_sky_sector_bits"), len(sky_bits)))
    for i in range(0, len(sky_bits), 16):
        lines.append("    %s," % ",".join(str(value) for value in sky_bits[i:i + 16]))
    lines.append("};")
    lines.append("")

    lines.append("const BspMapData g_%s_map = {" % prefix)
    lines.append("    %s, %s, %s," %
                 (sym("bsp_vertices"), sym("bsp_segs"), sym("bsp_seg_wall_len")))
    lines.append("    %s, %s, %s, %s," %
                 (sym("bsp_subsectors"), sym("bsp_subsector_sector"),
                  sym("bsp_nodes"), sym("bsp_things")))
    lines.append("    %s, %s, %s, %s," %
                  (sym("bsp_grid_cell_offsets"), sym("bsp_grid_seg_indices"),
                   sym("bsp_secret_sector_bits"), sym("bsp_sky_sector_bits")))
    lines.append("    %s, %s," %
                 (sym("bsp_automap_lines"), sym("bsp_seg_automap_lines")))
    lines.append("    %du, %du, %du, %du, %du, %du, %du, %du, %du, %du," %
                 (root, len(out_segs), len(vertices), len(map_data.out_ssectors),
                   len(nodes), map_data.next_door_group, len(map_data.out_things),
                   len(map_data.sectors), len(secret_sector_ids),
                   len(map_data.automap_lines)))
    lines.append("    %d, %d, %du, %du," % (grid_min_x, grid_min_y, grid_w, grid_h))
    lines.append("    %d, %d, %d, %d," %
                 (min(x for x, _ in vertices), min(y for _, y in vertices),
                  max(x for x, _ in vertices), max(y for _, y in vertices)))
    lines.append("    %d, %d, %du" %
                 (map_data.start_x, map_data.start_y, map_data.start_angle))
    lines.append("};")
    lines.append("")
    lines.append("#endif // !BSP_USE_HAND_MAP")
    lines.append("")

    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines))

    return EmitReport(
        root=root,
        grid_width=grid_w,
        grid_height=grid_h,
        grid_ref_count=len(grid_indices),
        spatial_checks=spatial_checks,
    )
