#!/usr/bin/env python3
"""Render a flattened Doom map (doom_map.MapData) plus its resolved texture
ids (from world_assets.emit_world_assets) as MegalDoom's generated_<map>_map.c.

Also builds and validates the runtime collision/LOS blockmap: that array is
pure emission output (baked once, read every frame by the renderer), so it is
derived here rather than inside doom_map.load_map().
"""

import os
from dataclasses import dataclass

from doom_map import validate_spatial_grid

WALL_TEX_DIM = None  # set by set_wall_tex_dim() before emit_map_c() is called


def set_wall_tex_dim(value):
    global WALL_TEX_DIM
    WALL_TEX_DIM = value


@dataclass
class EmitReport:
    root: int
    grid_width: int
    grid_height: int
    grid_ref_count: int
    spatial_checks: int


def emit_map_c(path, wad_path, map_data, texture_ids, texture_meta):
    out_segs = map_data.out_segs
    vertices = map_data.vertices
    nodes = map_data.nodes

    for seg in out_segs:
        name = seg["texture_name"]
        if not -32768 <= seg["tex_u_offset"] <= 32767:
            raise SystemExit("texture U offset out of s16 range: %d" % seg["tex_u_offset"])
        seg["tex"] = texture_ids[name]
        seg["tex_v"] = ((seg["tex_v_offset"] * WALL_TEX_DIM) //
                        texture_meta[name]["height"]) & (WALL_TEX_DIM - 1)

    root = (len(nodes) - 1) if nodes else 0x8000

    lines = []
    lines.append("// Generated by tools/wad-map-extract.py")
    lines.append("// Source: %s  map: %s" % (os.path.basename(wad_path), map_data.mapn))
    lines.append("// Generated at: source-derived")
    lines.append("#include \"bsp_map.h\"")
    lines.append("")
    lines.append("#if !BSP_USE_HAND_MAP")
    lines.append("")

    # Vertices (full original array; segs/nodes reference these indices).
    lines.append("const BspVertex bsp_vertices[%d] = {" % len(vertices))
    for (x, y) in vertices:
        lines.append("    {%d, %d}," % (x, y))
    lines.append("};")
    lines.append("")

    lines.append("const BspSeg bsp_segs[%d] = {" % len(out_segs))
    for s in out_segs:
        lines.append("    {%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d}," % (
            s["v1"], s["v2"], s["nx"], s["ny"], s["tex_u_offset"],
            s["tex_v"], s["tex"], s["type"], s["door_group"], s["required_key"],
            s["flags"]))
    lines.append("};")
    lines.append("")

    # Compact parallel ROM table: precomputed wall length per seg (|bx-ax| +
    # |by-ay|). Camera-independent, stored in ROM to avoid two vertex lookups
    # and two abs calls per seg visit in the renderer hot path.
    lines.append("const u16 bsp_seg_wall_len[%d] = {" % len(out_segs))
    for i, s in enumerate(out_segs):
        ax, ay = vertices[s["v1"]]
        bx, by = vertices[s["v2"]]
        wl = abs(bx - ax) + abs(by - ay)
        if i % 12 == 0:
            # Start a new visual row. The previous row needs a trailing comma
            # so consecutive rows stay valid C (adjacent numeric tokens like
            # "128\n    128" would otherwise be a syntax error). The very first
            # row (i == 0) has no predecessor to terminate.
            if i > 0:
                lines[-1] += ","
            lines.append("    %d" % wl)
        else:
            lines[-1] += ",%d" % wl
    lines[-1] += ","
    lines.append("};")
    lines.append("")

    # Uniform 256-unit blockmap used by runtime collision and LOS.  A segment is
    # referenced by every cell touched by its AABB; the exact segment tests remain
    # authoritative, so this is a conservative broad phase rather than a geometry
    # approximation.  All arrays are const and therefore live in cartridge ROM.
    grid_cell = 256
    grid_min_x = (min(x for x, _ in vertices) // grid_cell) * grid_cell
    grid_min_y = (min(y for _, y in vertices) // grid_cell) * grid_cell
    grid_max_x = (max(x for x, _ in vertices) // grid_cell) * grid_cell
    grid_max_y = (max(y for _, y in vertices) // grid_cell) * grid_cell
    grid_w = ((grid_max_x - grid_min_x) // grid_cell) + 1
    grid_h = ((grid_max_y - grid_min_y) // grid_cell) + 1
    grid_cells = [[] for _ in range(grid_w * grid_h)]
    for seg_index, s in enumerate(out_segs):
        ax, ay = vertices[s["v1"]]
        bx, by = vertices[s["v2"]]
        cx0 = (min(ax, bx) - grid_min_x) // grid_cell
        cx1 = (max(ax, bx) - grid_min_x) // grid_cell
        cy0 = (min(ay, by) - grid_min_y) // grid_cell
        cy1 = (max(ay, by) - grid_min_y) // grid_cell
        for cy in range(cy0, cy1 + 1):
            for cx in range(cx0, cx1 + 1):
                grid_cells[cy * grid_w + cx].append(seg_index)

    grid_offsets = [0]
    grid_indices = []
    for cell in grid_cells:
        grid_indices.extend(cell)
        grid_offsets.append(len(grid_indices))

    spatial_checks = validate_spatial_grid(
        vertices, out_segs, grid_min_x, grid_min_y, grid_w, grid_h,
        grid_cell, grid_cells, map_data.start_x, map_data.start_y)

    lines.append("const s16 bsp_grid_min_x = %d;" % grid_min_x)
    lines.append("const s16 bsp_grid_min_y = %d;" % grid_min_y)
    lines.append("const u16 bsp_grid_width = %du;" % grid_w)
    lines.append("const u16 bsp_grid_height = %du;" % grid_h)
    lines.append("const u16 bsp_grid_cell_offsets[%d] = {" % len(grid_offsets))
    for i in range(0, len(grid_offsets), 12):
        lines.append("    %s," % ",".join(str(v) for v in grid_offsets[i:i + 12]))
    lines.append("};")
    lines.append("const u16 bsp_grid_seg_indices[%d] = {" % len(grid_indices))
    for i in range(0, len(grid_indices), 12):
        lines.append("    %s," % ",".join(str(v) for v in grid_indices[i:i + 12]))
    lines.append("};")
    lines.append("const s16 bsp_map_min_x = %d;" % min(x for x, _ in vertices))
    lines.append("const s16 bsp_map_min_y = %d;" % min(y for _, y in vertices))
    lines.append("const s16 bsp_map_max_x = %d;" % max(x for x, _ in vertices))
    lines.append("const s16 bsp_map_max_y = %d;" % max(y for _, y in vertices))
    lines.append("")

    lines.append("const BspSubsector bsp_subsectors[%d] = {" % len(map_data.out_ssectors))
    for first, count in map_data.out_ssectors:
        lines.append("    {%d, %d}," % (first, count))
    lines.append("};")
    lines.append("const u16 bsp_subsector_sector[%d] = {" % len(map_data.out_ssector_sectors))
    for i in range(0, len(map_data.out_ssector_sectors), 16):
        lines.append("    %s," % ",".join(
            str(value) for value in map_data.out_ssector_sectors[i:i + 16]))
    lines.append("};")
    lines.append("")

    lines.append("const BspNode bsp_nodes[%d] = {" % len(nodes))
    for nd in nodes:
        lines.append("    {%d, %d, %d, %d, {%d, %d, %d, %d}, {%d, %d, %d, %d}, %du, %du}," % (
            nd["x"], nd["y"], nd["dx"], nd["dy"],
            *nd["front_box"], *nd["back_box"], nd["front"], nd["back"]))
    lines.append("};")
    lines.append("")

    lines.append("const u16 bsp_root_node = %du;" % root)
    lines.append("const u16 bsp_seg_count = %du;" % len(out_segs))
    lines.append("const u16 bsp_vertex_count = %du;" % len(vertices))
    lines.append("const u16 bsp_subsector_count = %du;" % len(map_data.out_ssectors))
    lines.append("const u16 bsp_node_count = %du;" % len(nodes))
    lines.append("const u16 bsp_door_count = %du;" % map_data.next_door_group)
    lines.append("const BspThing bsp_things[%d] = {" % len(map_data.out_things))
    for x, y, thing_type, angle, flags in map_data.out_things:
        lines.append("    {%d, %d, %du, %du, %du}," %
                     (x, y, thing_type, angle, flags))
    lines.append("};")
    lines.append("const u16 bsp_thing_count = %du;" % len(map_data.out_things))
    lines.append("const s32 bsp_player_start_x = %d;" % map_data.start_x)
    lines.append("const s32 bsp_player_start_y = %d;" % map_data.start_y)
    lines.append("const u16 bsp_player_start_angle = %du;" % map_data.start_angle)
    lines.append("")
    lines.append("#endif // !BSP_USE_HAND_MAP")
    lines.append("")

    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines))

    return EmitReport(
        root=root,
        grid_width=grid_w,
        grid_height=grid_h,
        grid_ref_count=len(grid_indices),
        spatial_checks=spatial_checks,
    )
