param(
    [switch]$Setup,
    [switch]$Debug
)

$ErrorActionPreference = "Stop"
$Root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$Source = Join-Path $Root ".externals\blastem"
$Toolchain = Join-Path $Root ".externals\toolchain"
$Output = Join-Path $Source "build\windows"
$RunnerPatch = Join-Path $PSScriptRoot "blastem-runner.patch"
$RunnerSentinel = "MEGALDOOM_RUNNER_VERSION 4"

if ($Setup) { & (Join-Path $PSScriptRoot "setup-blastem-toolchain.ps1"); if ($LASTEXITCODE) { exit $LASTEXITCODE } }
if (-not (Test-Path (Join-Path $Source "Makefile"))) { throw "BlastEm source is missing at $Source." }
if (-not (Test-Path (Join-Path $Source "megaldoom_runner.c"))) {
    Push-Location $Root
    try {
        & git apply --check --directory=.externals/blastem $RunnerPatch
        if ($LASTEXITCODE -ne 0) { throw "The deterministic-runner patch no longer applies cleanly." }
        & git apply --directory=.externals/blastem $RunnerPatch
        if ($LASTEXITCODE -ne 0) { throw "Could not apply the deterministic-runner patch." }
    } finally { Pop-Location }
}
if (-not (Select-String -LiteralPath (Join-Path $Source "megaldoom_runner.c") -SimpleMatch $RunnerSentinel -Quiet)) {
    throw "BlastEm deterministic runner is stale; apply the current tools/blastem-runner.patch."
}

$clang = Get-ChildItem -Path (Join-Path $Toolchain "llvm-mingw") -Filter "x86_64-w64-mingw32-clang.exe" -Recurse | Select-Object -First 1
$windres = Get-ChildItem -Path (Join-Path $Toolchain "llvm-mingw") -Filter "llvm-windres.exe" -Recurse | Select-Object -First 1
$sdl = Get-ChildItem -Path (Join-Path $Toolchain "SDL2") -Directory -Recurse | Where-Object { $_.Name -eq "x86_64-w64-mingw32" } | Select-Object -First 1
$glew = Join-Path $Toolchain "glew"
if (-not $clang -or -not $windres -or -not $sdl -or -not (Test-Path (Join-Path $glew "include\GL\glew.h"))) {
    throw "Toolchain is incomplete. Run: pwsh -NoProfile -File tools/setup-blastem-toolchain.ps1"
}

# BlastEm's Makefile already has a Windows target; pass every path explicitly
# so no global MinGW/MSYS installation leaks into the build.
$wsl = Get-Command wsl.exe -ErrorAction SilentlyContinue
if (-not $wsl) { throw "WSL with GNU make is required to drive this portable Windows toolchain." }

# A failed wslpath conversion silently yields an empty string here, which then
# turns "cd '$sourceWsl'" into "cd ''" (WSL's home directory) and surfaces as a
# confusing "no rule to make target" instead of naming the real problem. Check
# each conversion explicitly so a broken toolchain path fails clearly.
function Convert-ToWslPath([string]$WindowsPath, [string]$Description) {
    $converted = (& wsl.exe -- wslpath -a ($WindowsPath -replace '\\', '/')).Trim()
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($converted)) {
        throw "Could not convert $Description path to a WSL path: $WindowsPath"
    }
    return $converted
}
# $sourceWsl/$clangWsl/$windresWsl are consumed by WSL's own bash/make (cd and
# exec), so they need WSL-style paths. SDL2_PREFIX/GLEW_PREFIX, however, only
# ever reach x86_64-w64-mingw32-clang.exe as -I/-L flags -- that's a native
# Windows binary invoked *from* WSL, and it does not understand /mnt/c-style
# paths (confirmed: passing a WSL path here fails with "SDL.h file not found"
# even though the file exists and is readable from WSL). Keep these two as
# plain Windows paths; the Makefile's forward-slash concatenation onto them
# (e.g. "$(SDL2_PREFIX)/include/$(SDL_UPPER)") mixes separators, which clang
# accepts fine on Windows.
$sourceWsl = Convert-ToWslPath $Source "BlastEm source"
$clangWsl = Convert-ToWslPath $clang.FullName "clang compiler"
$windresWsl = Convert-ToWslPath $windres.FullName "windres"
# Forward slashes, not backslashes: GLEW32S_LIB is composed from GLEW_PREFIX
# and used unquoted in the Makefile's link recipe (LDFLAGS+= $(GLEW32S_LIB) ...),
# so a backslash-laden Windows path gets partially eaten as shell escapes when
# make hands the recipe to WSL's bash (e.g. "C:\Users" becomes "CUsers").
# Windows and clang both accept forward slashes, so this sidesteps the escaping
# issue without needing to touch the Makefile's quoting.
$sdlWindows = $sdl.FullName -replace '\\', '/'
$glewWindows = $glew -replace '\\', '/'
$makeArgs = "OS=Windows CPU=x86_64 CC='$clangWsl' WINDRES='$windresWsl' SDL2_PREFIX='$sdlWindows' GLEW_PREFIX='$glewWindows' NOLTO=1 NONUKLEAR=1"
if ($Debug) { $makeArgs += " DEBUG=1" }
# Dependency files are generated by the compiler and embed its path syntax.
# A previous native/WSL build can leave a Windows-style .d file that GNU make
# cannot parse before it has a chance to rebuild the object.  They are the
# only generated inputs removed here; sources and objects remain untouched.
$dependencyDir = Join-Path $Source "obj\release"
if (Test-Path $dependencyDir) {
    foreach ($dependency in (Get-ChildItem -LiteralPath $dependencyDir -Filter "*.d" -File)) {
        Remove-Item -LiteralPath $dependency.FullName -Force
    }
}
$makeCommand = "set -e; command -v make >/dev/null; cd '$sourceWsl'; make $makeArgs blastem.exe"
& wsl.exe -- bash -lc $makeCommand
if ($LASTEXITCODE -ne 0) { throw "BlastEm Windows build failed." }

New-Item -ItemType Directory -Path $Output -Force | Out-Null
Copy-Item (Join-Path $Source "blastem.exe") (Join-Path $Output "blastem.exe") -Force
$sdlDll = Get-ChildItem -Path $sdl.FullName -Filter "SDL2.dll" -Recurse | Select-Object -First 1
if ($sdlDll) { Copy-Item $sdlDll.FullName (Join-Path $Output "SDL2.dll") -Force }
foreach ($runtimeFile in @("default.cfg", "systems.cfg", "rom.db", "menu.bin", "gamecontrollerdb.txt")) {
    $runtimeSource = Join-Path $Source $runtimeFile
    if (Test-Path $runtimeSource) { Copy-Item $runtimeSource (Join-Path $Output $runtimeFile) -Force }
}
$shadersSource = Join-Path $Source "shaders"
if (Test-Path $shadersSource) { Copy-Item $shadersSource (Join-Path $Output "shaders") -Recurse -Force }

Write-Host "Custom Windows BlastEm built:" -ForegroundColor Green
Write-Host "  $(Join-Path $Output 'blastem.exe')"
