param(
    [string]$TexturePath = ".extenals\freedoom\patches\stonew1.png"
)

$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$SourcePath = Join-Path $Root $TexturePath
$OutPath = Join-Path $Root "src\generated_assets.h"

if (-not (Test-Path $SourcePath)) {
    throw "Texture source not found: $SourcePath"
}

Add-Type -AssemblyName System.Drawing

$palette = @(
    @(0x00, 0x00, 0x00),
    @(0xE0, 0xE0, 0xE0),
    @(0x20, 0x20, 0x20),
    @(0x40, 0x40, 0x40),
    @(0x68, 0x68, 0x68),
    @(0x90, 0x90, 0x90),
    @(0xB8, 0xB8, 0xB8),
    @(0xE0, 0xE0, 0xE0),
    @(0x20, 0x30, 0x50),
    @(0x30, 0x68, 0xA0),
    @(0x50, 0xA0, 0xD0),
    @(0xE0, 0xE0, 0x70),
    @(0x90, 0x40, 0x40),
    @(0xC0, 0x68, 0x48),
    @(0x30, 0x50, 0x20),
    @(0x50, 0x70, 0x30)
)

function Get-NearestPaletteIndex([System.Drawing.Color]$Color) {
    $bestIndex = 0
    $bestDistance = [int]::MaxValue

    for ($i = 0; $i -lt $palette.Count; $i++) {
        $dr = [int]$Color.R - $palette[$i][0]
        $dg = [int]$Color.G - $palette[$i][1]
        $db = [int]$Color.B - $palette[$i][2]
        $distance = ($dr * $dr) + ($dg * $dg) + ($db * $db)

        if ($distance -lt $bestDistance) {
            $bestDistance = $distance
            $bestIndex = $i
        }
    }

    return $bestIndex
}

$image = [System.Drawing.Bitmap]::new($SourcePath)
try {
    $rows = New-Object System.Collections.Generic.List[string]

    for ($y = 0; $y -lt 8; $y++) {
        $values = New-Object System.Collections.Generic.List[string]

        for ($x = 0; $x -lt 8; $x++) {
            $srcX = [Math]::Min($image.Width - 1, [int](($x * $image.Width) / 8))
            $srcY = [Math]::Min($image.Height - 1, [int](($y * $image.Height) / 8))
            $index = Get-NearestPaletteIndex $image.GetPixel($srcX, $srcY)
            $values.Add($index.ToString())
        }

        $rows.Add("    {" + ($values -join ", ") + "}")
    }
} finally {
    $image.Dispose()
}

$relativeSource = $TexturePath.Replace("\", "/")
$generatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")
$content = @"
#ifndef MEGALDOOM_GENERATED_ASSETS_H
#define MEGALDOOM_GENERATED_ASSETS_H

#include <genesis.h>

// Generated by tools/convert-freedoom-assets.ps1.
// Source: $relativeSource
// Generated at: $generatedAt
static const u8 FREEDOOM_WALL_TEXTURE[8][8] = {
$($rows -join ",`r`n")
};

#endif
"@

Set-Content -Path $OutPath -Value $content -NoNewline
Write-Host "Generated $OutPath from $TexturePath" -ForegroundColor Green
