param(
    [string]$TexturePath = ".extenals\freedoom\patches\stonew1.png",
    [string]$BillboardPath = ".extenals\freedoom\sprites\bon1a0.png",
    [string]$BillboardKeyPath = ".extenals\freedoom\sprites\bkeya0.png",
    [string]$BillboardDecorPath = ".extenals\freedoom\sprites\bar1a0.png",
    [switch]$BillboardOnly
)

$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$SourcePath = Join-Path $Root $TexturePath
$BillboardSourcePath = Join-Path $Root $BillboardPath
$BillboardKeySourcePath = Join-Path $Root $BillboardKeyPath
$BillboardDecorSourcePath = Join-Path $Root $BillboardDecorPath
$OutPath = Join-Path $Root "src\generated_assets.h"
$BillboardOutPath = Join-Path $Root "src\generated_billboard_assets.h"

if (-not (Test-Path $SourcePath)) {
    throw "Texture source not found: $SourcePath"
}
if (-not (Test-Path $BillboardSourcePath)) {
    throw "Billboard source not found: $BillboardSourcePath"
}
if (-not (Test-Path $BillboardKeySourcePath)) {
    throw "Billboard key source not found: $BillboardKeySourcePath"
}
if (-not (Test-Path $BillboardDecorSourcePath)) {
    throw "Billboard decor source not found: $BillboardDecorSourcePath"
}

Add-Type -AssemblyName System.Drawing

$palette = @(
    @(0x00, 0x00, 0x00),
    @(0xE0, 0xE0, 0xE0),
    @(0x20, 0x20, 0x20),
    @(0x40, 0x40, 0x40),
    @(0x68, 0x68, 0x68),
    @(0x90, 0x90, 0x90),
    @(0xB8, 0xB8, 0xB8),
    @(0xE0, 0xE0, 0xE0),
    @(0x20, 0x30, 0x50),
    @(0x30, 0x68, 0xA0),
    @(0x50, 0xA0, 0xD0),
    @(0xE0, 0xE0, 0x70),
    @(0x90, 0x40, 0x40),
    @(0xC0, 0x68, 0x48),
    @(0x30, 0x50, 0x20),
    @(0x50, 0x70, 0x30)
)

function Get-NearestPaletteIndex([System.Drawing.Color]$Color) {
    $bestIndex = 0
    $bestDistance = [int]::MaxValue

    for ($i = 0; $i -lt $palette.Count; $i++) {
        $dr = [int]$Color.R - $palette[$i][0]
        $dg = [int]$Color.G - $palette[$i][1]
        $db = [int]$Color.B - $palette[$i][2]
        $distance = ($dr * $dr) + ($dg * $dg) + ($db * $db)

        if ($distance -lt $bestDistance) {
            $bestDistance = $distance
            $bestIndex = $i
        }
    }

    return $bestIndex
}

function Convert-Image8x8([string]$Path, [bool]$UseAlphaTransparency) {
    $image = [System.Drawing.Bitmap]::new($Path)
    $rows = New-Object System.Collections.Generic.List[string]

    try {
        for ($y = 0; $y -lt 8; $y++) {
            $values = New-Object System.Collections.Generic.List[string]

            for ($x = 0; $x -lt 8; $x++) {
                $srcX = [Math]::Min($image.Width - 1, [int](($x * $image.Width) / 8))
                $srcY = [Math]::Min($image.Height - 1, [int](($y * $image.Height) / 8))
                $pixel = $image.GetPixel($srcX, $srcY)
                $index = 0

                if ((-not $UseAlphaTransparency) -or ($pixel.A -ge 128)) {
                    $index = Get-NearestPaletteIndex $pixel
                    if ($UseAlphaTransparency -and ($index -eq 0)) {
                        $index = 2
                    }
                }

                $values.Add($index.ToString())
            }

            $rows.Add("    {" + ($values -join ", ") + "}")
        }
    } finally {
        $image.Dispose()
    }

    return $rows
}

$wallRows = Convert-Image8x8 $SourcePath $false
$billboardRows = Convert-Image8x8 $BillboardSourcePath $true
$billboardKeyRows = Convert-Image8x8 $BillboardKeySourcePath $true
$billboardDecorRows = Convert-Image8x8 $BillboardDecorSourcePath $true
$relativeSource = $TexturePath.Replace("\", "/")
$relativeBillboardSource = $BillboardPath.Replace("\", "/")
$relativeBillboardKeySource = $BillboardKeyPath.Replace("\", "/")
$relativeBillboardDecorSource = $BillboardDecorPath.Replace("\", "/")
$generatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")

$billboardContent = @"
#ifndef MEGALDOOM_GENERATED_BILLBOARD_ASSETS_H
#define MEGALDOOM_GENERATED_BILLBOARD_ASSETS_H

#include <genesis.h>

// Generated by tools/convert-freedoom-assets.ps1.
// Bonus billboard source: $relativeBillboardSource
// Key billboard source: $relativeBillboardKeySource
// Decor billboard source: $relativeBillboardDecorSource
// Generated at: $generatedAt
// Palette index 0 is transparent for billboard rendering.
static const u8 FREEDOOM_BILLBOARD_BONUS_TEXTURE[8][8] = {
$($billboardRows -join ",`r`n")
};

static const u8 FREEDOOM_BILLBOARD_KEY_TEXTURE[8][8] = {
$($billboardKeyRows -join ",`r`n")
};

static const u8 FREEDOOM_BILLBOARD_DECOR_TEXTURE[8][8] = {
$($billboardDecorRows -join ",`r`n")
};

#endif
"@

Set-Content -Path $BillboardOutPath -Value $billboardContent -NoNewline

if ($BillboardOnly) {
    Write-Host "Generated $BillboardOutPath from $BillboardPath, $BillboardKeyPath and $BillboardDecorPath" -ForegroundColor Green
    return
}

$content = @"
#ifndef MEGALDOOM_GENERATED_ASSETS_H
#define MEGALDOOM_GENERATED_ASSETS_H

#include <genesis.h>

// Generated by tools/convert-freedoom-assets.ps1.
// Source: $relativeSource
// Generated at: $generatedAt
static const u8 FREEDOOM_WALL_TEXTURE[8][8] = {
$($wallRows -join ",`r`n")
};

#endif
"@

try {
    Set-Content -Path $OutPath -Value $content -NoNewline
    Write-Host "Generated $OutPath from $TexturePath" -ForegroundColor Green
} catch {
    Write-Warning "Could not update $OutPath. The existing wall texture header was left unchanged. $($_.Exception.Message)"
}
Write-Host "Generated $BillboardOutPath from $BillboardPath, $BillboardKeyPath and $BillboardDecorPath" -ForegroundColor Green
