#!/usr/bin/env python3
"""Parse, flatten, certify and atomically emit a Doom map for MegalDoom.

Doom's prebuilt VERTEXES/SEGS/SSECTORS/NODES map almost 1:1 onto our Bsp*
structs (even the 0x8000 subsector-leaf bit is identical), so we convert them
directly -- no on-device node builder needed.

This is the CLI entry point only: it wires together wad_reader.py (raw WAD
lump access), doom_map.py (parse + flatten + certify one map), world_assets.py
(bake wall/flat textures and PAL3) and bsp_emit.py (render the result as C),
then prints a report. See those modules for the actual logic.

Usage: python tools/wad-map-extract.py [--map E1M1] [--wad DOOM1.WAD]
"""

import argparse
from collections import Counter
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile

import bsp_emit
import doom_map
import world_assets
from wad_reader import WadFile
from wad_source import EXPECTED_CAMPAIGN_WAD_SHA256

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_WAD = os.path.join(PROJECT_ROOT, "DOOM1.WAD")
# Generated headers live beside the module that consumes them (src/<group>/).
DEFAULT_ASSET_OUT = os.path.join(PROJECT_ROOT, "src", "bsp", "generated_assets.h")
DEFAULT_MAP_OUT_DIR = os.path.join(PROJECT_ROOT, "src", "bsp")
DEFAULT_LIMITS_OUT = os.path.join(DEFAULT_MAP_OUT_DIR, "generated_map_limits.h")


bsp_emit.set_wall_tex_dims(world_assets.WALL_TEX_WIDTH,
                           world_assets.WALL_TEX_HEIGHT)


def ensure_extracted_assets(wad_path, wad_sha256):
    """Refresh the ignored PNG tree when its source WAD fingerprint changes."""
    asset_root = os.path.join(PROJECT_ROOT, "res", "originaldoom")
    marker_name = ".wad-source-sha256"
    marker = os.path.join(asset_root, marker_name)
    try:
        with open(marker, "r", encoding="ascii") as handle:
            if handle.read().strip().upper() == wad_sha256:
                return False
    except OSError:
        pass

    parent = os.path.dirname(asset_root)
    staged = tempfile.mkdtemp(prefix=".originaldoom-stage-", dir=parent)
    backup = os.path.join(parent, ".originaldoom-backup")
    try:
        subprocess.check_call([
            sys.executable, os.path.join(PROJECT_ROOT, "tools", "wad-extract.py"),
            "--wad", os.path.abspath(wad_path), "--out", staged,
        ])
        with open(os.path.join(staged, marker_name), "w", encoding="ascii",
                  newline="\n") as handle:
            handle.write(wad_sha256 + "\n")
        if os.path.exists(backup):
            shutil.rmtree(backup)
        if os.path.exists(asset_root):
            os.replace(asset_root, backup)
        os.replace(staged, asset_root)
        if os.path.exists(backup):
            shutil.rmtree(backup)
        return True
    except Exception:
        if not os.path.exists(asset_root) and os.path.exists(backup):
            os.replace(backup, asset_root)
        raise
    finally:
        if os.path.exists(staged):
            shutil.rmtree(staged)


def active_thing_count(map_data, skill_mask):
    return sum(
        1 for _, _, thing_type, _, flags in map_data.out_things
        if thing_type in doom_map.RUNTIME_THING_TYPES and
        (flags & skill_mask) != 0 and (flags & 0x0010) == 0
    )


def emit_limits(path, maps):
    movement_margin = 512
    for map_data in maps:
        coordinates = ([vertex[0] for vertex in map_data.vertices] +
                       [vertex[1] for vertex in map_data.vertices] +
                       [thing[0] for thing in map_data.out_things] +
                       [thing[1] for thing in map_data.out_things])
        if (min(coordinates) < -32768 + movement_margin or
                max(coordinates) > 32767 - movement_margin):
            raise SystemExit(
                "%s object coordinates do not fit s16 with %d-unit movement margin" %
                (map_data.mapn, movement_margin))
    active_max = max(active_thing_count(map_data, skill_mask)
                     for map_data in maps for skill_mask in (1, 2, 4))
    values = {
        "MAP_COUNT": len(maps),
        "MAP_MAX_SEGS": max(len(map_data.out_segs) for map_data in maps),
        "MAP_MAX_VERTICES": max(len(map_data.vertices) for map_data in maps),
        "MAP_MAX_SUBSECTORS": max(len(map_data.out_ssectors) for map_data in maps),
        "MAP_MAX_NODES": max(len(map_data.nodes) for map_data in maps),
        "MAP_MAX_SECTORS": max(len(map_data.sectors) for map_data in maps),
        "MAP_MAX_ACTIVE_THINGS": active_max,
    }
    if values["MAP_MAX_ACTIVE_THINGS"] > 255:
        raise SystemExit("active THING count exceeds u8 registry index capacity")
    lines = [
        "#ifndef MEGALDOOM_GENERATED_MAP_LIMITS_H",
        "#define MEGALDOOM_GENERATED_MAP_LIMITS_H",
        "",
        "// Generated by tools/wad-map-extract.py for the shipped map set.",
    ]
    for name, value in values.items():
        lines.append("#define MEGALDOOM_%s %d" % (name, value))
    lines.extend(["", "#endif", ""])
    with open(path, "w", newline="\n") as handle:
        handle.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--wad", default=DEFAULT_WAD)
    ap.add_argument("--map", default="E1M1")
    ap.add_argument("--maps", nargs="+", default=None,
                    help="atomically emit a shared atlas and multiple map descriptors")
    ap.add_argument("--out", default=None)
    ap.add_argument("--assets-out", default=DEFAULT_ASSET_OUT)
    ap.add_argument("--limits-out", default=DEFAULT_LIMITS_OUT)
    ap.add_argument("--map-out-dir", default=DEFAULT_MAP_OUT_DIR,
                    help="output directory for --maps generated C descriptors")
    ap.add_argument("--no-recipes", action="store_true",
                    help="disable curated material transfers for a clean-WAD A/B baseline")
    ap.add_argument("--certify-only", action="store_true",
                    help="parse/classify/certify and report without emitting files")
    args = ap.parse_args()

    wad = WadFile(args.wad)
    mapn = args.map.upper()
    out_path = args.out or os.path.join(
        DEFAULT_MAP_OUT_DIR, "generated_%s_map.c" % mapn.lower()
    )

    map_data = doom_map.load_map(wad, mapn, apply_recipes=not args.no_recipes)

    if args.certify_only:
        print("Map %s flat progression certified" % mapn)
        print("  doors    : %d groups, faces=%s" %
              (map_data.next_door_group, dict(sorted(map_data.door_face_counts.items()))))
        print("  keys     : available=0x%02X required=0x%02X reached=%s" %
              (map_data.certificate["available_keys"], map_data.required_key_mask,
               map_data.certificate["reached_masks"]))
        print("  exit     : seg %d with key mask=0x%02X after %d states" %
              (map_data.certificate["exit_index"], map_data.certificate["key_mask"],
               map_data.certificate["states"]))
        print("  textures : %d door faces still require fallback" %
              map_data.fallback_door_faces)
        print("  source   : SHA-256 %s" % map_data.wad_sha256)
        print("  material : baseline/final=%d/%d, targets=%s (%d retextured SEGs)" %
              (map_data.baseline_seg_count, len(map_data.out_segs),
               map_data.curated_material_linedefs,
               map_data.curated_material_segs))
        for transfer in map_data.curated_material_reports:
            print("             %s source %d (hint %d) -> %s, %s, +%d SEGs" %
                  (transfer["name"], transfer["source_linedef"],
                   transfer["source_linedef_hint"],
                   transfer["target_linedefs"], transfer["texture"],
                   transfer["added_segs"]))
        return

    if args.maps:
        map_names = [name.upper() for name in args.maps]
        campaign_maps = [doom_map.load_map(
            wad, name, apply_recipes=not args.no_recipes) for name in map_names]
        wad_sha256 = hashlib.sha256(wad.data).hexdigest().upper()
        if wad_sha256 != EXPECTED_CAMPAIGN_WAD_SHA256:
            raise SystemExit(
                "campaign WAD SHA-256 mismatch: expected %s, got %s" %
                (EXPECTED_CAMPAIGN_WAD_SHA256, wad_sha256))
        refreshed_assets = ensure_extracted_assets(args.wad, wad_sha256)

        combined_usage = Counter()
        for campaign_map in campaign_maps:
            combined_usage.update(campaign_map.texture_usage)
        door_texture_names = {
            seg["texture_name"]
            for campaign_map in campaign_maps
            for seg in campaign_map.out_segs
            if seg["type"] == doom_map.SEG_DOOR
        }
        sector_owner = max(campaign_maps, key=lambda value: len(value.sectors))

        temp_paths = []
        asset_temp = args.assets_out + ".tmp"
        limits_temp = args.limits_out + ".tmp"
        temp_paths.extend((asset_temp, limits_temp))
        map_outputs = []
        for campaign_map in campaign_maps:
            target = os.path.join(
                args.map_out_dir,
                "generated_%s_map.c" % campaign_map.mapn.lower())
            map_outputs.append((campaign_map, target, target + ".tmp"))
            temp_paths.append(target + ".tmp")
        for temp_path in temp_paths:
            if os.path.exists(temp_path):
                os.remove(temp_path)

        texture_ids, texture_meta, _, palette = world_assets.emit_world_assets(
            asset_temp, combined_usage, sector_owner.sectors, None,
            door_texture_names)
        reports = []
        for campaign_map, _, temp in map_outputs:
            reports.append(bsp_emit.emit_map_c(
                temp, args.wad, campaign_map, texture_ids, texture_meta))
        emit_limits(limits_temp, campaign_maps)

        os.replace(asset_temp, args.assets_out)
        os.replace(limits_temp, args.limits_out)
        for _, target, temp in map_outputs:
            os.replace(temp, target)

        print("Wrote shared %d-texture atlas for %s" %
              (len(texture_ids), ", ".join(map_names)))
        for campaign_map, report in zip(campaign_maps, reports):
            print("  %s: %d vertices, %d segs, %d subsectors, %d nodes, "
                  "%d things, %d secrets, blockmap %dx%d" % (
                      campaign_map.mapn, len(campaign_map.vertices),
                      len(campaign_map.out_segs), len(campaign_map.out_ssectors),
                      len(campaign_map.nodes), len(campaign_map.out_things),
                      sum(1 for sector in campaign_map.sectors
                          if sector["special"] == 9),
                      report.grid_width, report.grid_height))
        print("  source: SHA-256 %s" % wad_sha256)
        print("  extracted PNGs: %s" %
              ("refreshed atomically" if refreshed_assets else "fingerprint current"))
        print("  palette: %s" % " ".join(
            "%02X%02X%02X" % color for color in palette))
        return

    asset_temp = args.assets_out + ".tmp"
    map_temp = out_path + ".tmp"
    for temp_path in (asset_temp, map_temp):
        if os.path.exists(temp_path):
            os.remove(temp_path)
    texture_ids, texture_meta, sector_visuals, palette = world_assets.emit_world_assets(
        asset_temp, map_data.texture_usage, map_data.sectors, map_data,
        {seg["texture_name"] for seg in map_data.out_segs
         if seg["type"] == doom_map.SEG_DOOR})
    report = bsp_emit.emit_map_c(map_temp, args.wad, map_data, texture_ids, texture_meta)
    os.replace(asset_temp, args.assets_out)
    os.replace(map_temp, out_path)

    print("Wrote %s" % out_path)
    print("  vertices : %d" % len(map_data.vertices))
    print("  segs     : %d flat solid/interactive (of %d source)" %
          (len(map_data.out_segs), map_data.source_seg_count))
    print("  linedefs : %d" % len(map_data.linedefs))
    print("  sectors  : %d" % len(map_data.sectors))
    print("  textures : %d exact + fallback" % (len(texture_ids) - 1))
    print("  palette  : %s" % " ".join("%02X%02X%02X" % color for color in palette))
    print("  assets   : %s" % args.assets_out)
    print("  subsectors: %d" % len(map_data.out_ssectors))
    print("  nodes    : %d (root=%d)" % (len(map_data.nodes), report.root))
    print("  blockmap : %dx%d, %d refs, %d validation queries" %
          (report.grid_width, report.grid_height, report.grid_ref_count,
           report.spatial_checks))
    print("  player   : (%d,%d) angle_deg=%d -> %d" % (
        map_data.start_x, map_data.start_y, map_data.start_angle_deg,
        map_data.start_angle))
    print("  things   : %d raw, %d curated, %d skipped" %
          (len(map_data.out_things), map_data.supported_things,
           len(map_data.out_things) - map_data.supported_things))
    print("  doors    : %d groups, faces=%s, fallback faces=%d" %
          (map_data.next_door_group, dict(sorted(map_data.door_face_counts.items())),
           map_data.fallback_door_faces))
    print("  source   : SHA-256 %s" % map_data.wad_sha256)
    print("  material : baseline/final=%d/%d, targets=%s (%d retextured SEGs)" %
          (map_data.baseline_seg_count, len(map_data.out_segs),
           map_data.curated_material_linedefs,
           map_data.curated_material_segs))
    for transfer in map_data.curated_material_reports:
        print("             %s source %d (hint %d) -> %s, %s, +%d SEGs" %
              (transfer["name"], transfer["source_linedef"],
               transfer["source_linedef_hint"],
               transfer["target_linedefs"], transfer["texture"],
               transfer["added_segs"]))
    print("  keys     : available=0x%02X required=0x%02X reached=%s" %
          (map_data.certificate["available_keys"], map_data.required_key_mask,
           map_data.certificate["reached_masks"]))
    print("  certified: exit seg %d reachable with key mask=0x%02X after %d states" %
          (map_data.certificate["exit_index"], map_data.certificate["key_mask"],
           map_data.certificate["states"]))


if __name__ == "__main__":
    main()
