#ifndef MEGALDOOM_GENERATED_BILLBOARD_ASSETS_H
#define MEGALDOOM_GENERATED_BILLBOARD_ASSETS_H

#include <genesis.h>

// Generated by tools/convert-freedoom-assets.ps1.
// Bonus billboard source: .extenals/freedoom/sprites/bon1a0.png
// Key billboard source: .extenals/freedoom/sprites/bkeya0.png
// Decor billboard source: .extenals/freedoom/sprites/bar1a0.png
// Generated at: 2026-06-23T21:49:12-03:00
// Palette index 0 is transparent for billboard rendering.
static const u8 FREEDOOM_BILLBOARD_BONUS_TEXTURE[8][8] = {
    {0, 0, 15, 11, 5, 15, 0, 0},
    {0, 0, 0, 2, 2, 0, 0, 0},
    {0, 0, 4, 5, 4, 3, 2, 0},
    {0, 5, 1, 5, 14, 2, 4, 0},
    {15, 15, 15, 14, 2, 2, 4, 14},
    {4, 14, 14, 14, 2, 2, 3, 14},
    {14, 2, 2, 2, 2, 2, 2, 2},
    {0, 3, 4, 4, 4, 3, 2, 0}
};

static const u8 FREEDOOM_BILLBOARD_KEY_TEXTURE[8][8] = {
    {0, 0, 0, 10, 6, 10, 10, 9},
    {0, 9, 8, 2, 2, 8, 8, 8},
    {8, 8, 3, 5, 5, 2, 8, 8},
    {0, 8, 4, 3, 3, 2, 8, 8},
    {0, 8, 8, 8, 8, 8, 2, 2},
    {0, 0, 2, 2, 2, 2, 8, 8},
    {0, 0, 8, 8, 2, 8, 2, 8},
    {0, 0, 0, 8, 8, 8, 2, 2}
};

static const u8 FREEDOOM_BILLBOARD_DECOR_TEXTURE[8][8] = {
    {0, 0, 2, 5, 6, 4, 0, 0},
    {2, 3, 2, 2, 2, 2, 2, 2},
    {2, 2, 2, 2, 2, 2, 2, 2},
    {2, 2, 2, 14, 15, 15, 4, 3},
    {0, 2, 2, 13, 11, 13, 2, 2},
    {0, 2, 3, 13, 13, 12, 2, 2},
    {2, 3, 3, 3, 3, 3, 3, 4},
    {2, 3, 3, 4, 4, 4, 3, 3}
};

#endif