#ifndef MEGALDOOM_GENERATED_ASSETS_H
#define MEGALDOOM_GENERATED_ASSETS_H

#include <genesis.h>

// Generated by tools/convert-freedoom-assets.ps1.
// Source: .extenals/freedoom/patches/stonew1.png
// Generated at: 2026-06-23T14:27:31-03:00
static const u8 FREEDOOM_WALL_TEXTURE[8][8] = {
    {3, 2, 3, 12, 15, 15, 12, 12},
    {3, 3, 3, 4, 3, 15, 3, 12},
    {3, 4, 3, 12, 12, 12, 3, 3},
    {3, 3, 4, 4, 3, 3, 12, 3},
    {4, 15, 15, 3, 3, 2, 2, 2},
    {2, 15, 12, 4, 2, 2, 3, 4},
    {15, 12, 3, 3, 15, 2, 3, 12},
    {4, 3, 3, 3, 12, 3, 4, 4}
};

#endif